import { z } from "zod";
import {
  facePortraitPrompt,
  faceVideoPrompt,
  personaForVoice,
} from "@/lib/agent-persona";
import { generateImage, generateVideo } from "@/lib/ai/grok";
import { getCompanyById } from "@/lib/server/company-context";
import { errorResponse, jsonOk, ApiError } from "@/lib/server/errors";
import { getSupabaseAdmin } from "@/lib/server/supabase-admin";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 120;

const Query = z.object({
  companyId: z.string().uuid(),
  /** Force a regenerate even when cached media exists. */
  refresh: z.coerce.boolean().optional(),
});

/**
 * The agent's face for calls, generated by Grok Imagine from the configured
 * voice. Cached on the company row and regenerated when the voice changes, so
 * the portrait and the voice can never disagree.
 *
 * Degrades to `{ available: false }` rather than erroring — a call must still
 * connect when image generation is unavailable (no key, quota, outage).
 */
export async function GET(req: Request) {
  try {
    const url = new URL(req.url);
    const { companyId, refresh } = Query.parse({
      companyId: url.searchParams.get("companyId"),
      refresh: url.searchParams.get("refresh") ?? undefined,
    });

    const company = await getCompanyById(companyId);
    const persona = personaForVoice(company.agent_voice);

    const cacheValid =
      !refresh &&
      company.agent_face_image_url &&
      company.agent_face_voice === persona.voice;

    if (cacheValid) {
      return jsonOk({
        available: true,
        cached: true,
        voice: persona.voice,
        presentation: persona.presentation,
        faceImageUrl: company.agent_face_image_url,
        faceVideoUrl: company.agent_face_video_url ?? undefined,
      });
    }

    const agentName = company.agent_name || "Atlas";

    let faceImageUrl: string | undefined;
    try {
      const image = await generateImage(facePortraitPrompt(persona, agentName));
      faceImageUrl = image.url ?? (image.b64 ? `data:image/png;base64,${image.b64}` : undefined);
    } catch (err) {
      console.warn("[agent-face] portrait generation failed", err);
    }

    if (!faceImageUrl) {
      return jsonOk({
        available: false,
        voice: persona.voice,
        presentation: persona.presentation,
        message:
          "Face generation unavailable — the call falls back to the initials avatar.",
      });
    }

    // The talking loop is a bonus; a still portrait is enough to take the call.
    let faceVideoUrl: string | undefined;
    try {
      const video = await generateVideo(faceVideoPrompt(persona, agentName));
      faceVideoUrl = video.url;
    } catch (err) {
      console.warn("[agent-face] talking loop generation failed", err);
    }

    try {
      await getSupabaseAdmin()
        .from("companies")
        .update({
          agent_face_image_url: faceImageUrl,
          agent_face_video_url: faceVideoUrl ?? null,
          agent_face_voice: persona.voice,
          agent_face_generated_at: new Date().toISOString(),
        })
        .eq("id", company.id);
    } catch (err) {
      // Serve the freshly generated media even if we could not cache it.
      console.warn("[agent-face] could not cache generated media", err);
    }

    return jsonOk({
      available: true,
      cached: false,
      voice: persona.voice,
      presentation: persona.presentation,
      faceImageUrl,
      faceVideoUrl,
    });
  } catch (err) {
    if (err instanceof z.ZodError) {
      return errorResponse(
        new ApiError("BAD_REQUEST", "companyId is required", {
          status: 400,
          details: err.flatten(),
        }),
      );
    }
    return errorResponse(err);
  }
}
