import type {
  ArchitectureData,
  CodeExampleData,
  ImageArtifactData,
  ImplementationPlanData,
  MessageArtifact,
  ProposalData,
} from "@/types/ui";
import { ArchitectureCard } from "./ArchitectureCard";

/**
 * Artifacts sit beside a message, flat on paper, separated by a rule rather
 * than wrapped in a box. Nothing an agent produces is allowed to disappear
 * silently, so every artifact type ends in something rendered.
 */
function Artifact({
  eyebrow,
  title,
  children,
}: {
  eyebrow: string;
  title?: string;
  children?: React.ReactNode;
}) {
  return (
    <section className="w-full">
      <p className="text-label">{eyebrow}</p>
      {title ? <h4 className="mt-1 text-title text-ink">{title}</h4> : null}
      {children}
    </section>
  );
}

export function ArtifactRenderer({ artifact }: { artifact: MessageArtifact }) {
  if (artifact.type === "architecture") {
    return <ArchitectureCard data={artifact.data as ArchitectureData} />;
  }

  if (artifact.type === "implementation_plan") {
    const data = artifact.data as ImplementationPlanData;
    const steps = Array.isArray(data?.steps) ? data.steps : [];
    return (
      <Artifact eyebrow="Implementation plan" title={data?.title}>
        {steps.length === 0 ? (
          <p className="mt-2 max-w-[46ch] text-body text-ink-2">
            This plan came back with no steps. Ask Atlas to plan the change again.
          </p>
        ) : (
          <ol className="mt-3 divide-y divide-rule border-t border-rule">
            {steps.map((step, i) => (
              <li key={`${step.title}-${i}`} className="flex gap-3 py-3">
                <span className="mono-ts tabular mt-0.5 w-5 shrink-0">
                  {String(i + 1).padStart(2, "0")}
                </span>
                <div className="min-w-0">
                  <p className="text-body font-medium text-ink">{step.title}</p>
                  {step.detail ? (
                    <p className="mt-0.5 max-w-[64ch] text-caption">{step.detail}</p>
                  ) : null}
                </div>
              </li>
            ))}
          </ol>
        )}
      </Artifact>
    );
  }

  if (artifact.type === "code") {
    const data = artifact.data as CodeExampleData;
    return (
      <Artifact eyebrow={data?.language || "Code"} title={data?.title}>
        <pre className="mt-2 overflow-x-auto rounded-[var(--radius-lg)] border border-rule bg-sunken p-3 font-mono text-xs leading-relaxed text-ink-2">
          <code>{data?.code ?? ""}</code>
        </pre>
      </Artifact>
    );
  }

  if (artifact.type === "image") {
    const data = artifact.data as ImageArtifactData;
    if (!data?.url) {
      return (
        <Artifact eyebrow="Image" title={data?.title}>
          <p className="mt-2 max-w-[46ch] text-body text-ink-2">
            This image did not finish generating. Ask Atlas to make it again.
          </p>
        </Artifact>
      );
    }
    return (
      <Artifact eyebrow="Image" title={data.title}>
        {/* Generated asset on a remote host: next/image would need a loader per host. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={data.url}
          alt={data.alt || data.title || "Diagram generated by Atlas"}
          className="mt-2 w-full max-w-full rounded-[var(--radius-lg)] border border-rule"
        />
      </Artifact>
    );
  }

  if (artifact.type === "proposal") {
    const data = artifact.data as ProposalData;
    const bullets = Array.isArray(data?.bullets) ? data.bullets : [];
    return (
      <Artifact eyebrow="Proposal" title={data?.title}>
        {data?.summary ? (
          <p className="mt-2 max-w-[64ch] text-body text-ink-2">{data.summary}</p>
        ) : null}
        {bullets.length > 0 && (
          <ul className="mt-3 space-y-1.5 border-t border-rule pt-3">
            {bullets.map((b) => (
              <li key={b} className="max-w-[64ch] text-body text-ink-2">
                {b}
              </li>
            ))}
          </ul>
        )}
      </Artifact>
    );
  }

  // An artifact type the UI does not draw yet still announces itself, so a
  // demo never quietly loses something the agent produced.
  return (
    <Artifact eyebrow="Attachment" title={artifact.title}>
      <p className="mt-1 mono-ts">{String(artifact.type)}</p>
    </Artifact>
  );
}
